name: flutter_app_agora
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  pin_code_fields: ^2.3.0+3
  agora_rtc_engine: ^1.0.5
  permission_handler: ^4.0.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  progress_dialog: ^1.2.0
  flushbar: ^1.5.0
  email_validator: ^1.0.3
  image_picker: ^0.6.2+2
  datetime_picker_formfield: ^1.0.0
  cached_network_image: ^2.0.0
  provider: ^3.1.0+1
  flutter_slidable: ^0.5.4
  timer_builder: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

